### ISSUE TITLE
Personal style

### ISSUE THREAD

**Issue by deartb** [jiangtj-lab/hexo-cake-moon-menu#8]
How can I change the **location** of **the icon** ?

**Comment by jiangtj** [comment]
If you need to change the distance from the bottom and right, can be added in a custom style file (https://github.com/theme-next/hexo-theme-next/blob/a7a948a08f48dbe48879e277703d75706aec18e5/_config.yml#L34)
```css
.moon-menu,.moon-menu-bg,.moon-menu-content {
  right: 20px !important;
  bottom: 20px !important;
}
```

If you want to lean to the left, you can add the following style
```css
.moon-menu,.moon-menu-bg,.moon-menu-content {
  left: 20px !important;
}
.moon-menu-item {
  left: unset !important;
  right: 1rem !important;
}
```

The current style of this piece is not very good, and may be adjusted in the future.
